[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.7
blur = true
option_as_alt = "Both"
decorations = "Buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 18

[general]
import = [
    "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]
