import = [
    "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.8
blur = true
option_as_alt = "Both"
decorations = "Buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 18
