import = [
    "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 0
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 16
